version: '3.3'

services:
  drupal:
    build: .
    ports:
      - 80:80
    restart: always

  database:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    env_file:
     - ./.env
    volumes:
        - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    restart: always
